# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudebar < Formula
  desc "Claude Code status bar for tmux"
  homepage "https://github.com/lableaks/claudebar"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LabLeaks/claudebar/releases/download/v0.1.0/claudebar_0.1.0_darwin_amd64.tar.gz"
      sha256 "b13cf8cb36145c2459d1e9b0de7d85ba81e8fce0458769c5bee9fb745e37307c"

      define_method(:install) do
        bin.install "claudebar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LabLeaks/claudebar/releases/download/v0.1.0/claudebar_0.1.0_darwin_arm64.tar.gz"
      sha256 "8c1891fe32fd6577e5f2fdc0a16d6da84732c9b923a3b915b2617bff5e5cb605"

      define_method(:install) do
        bin.install "claudebar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LabLeaks/claudebar/releases/download/v0.1.0/claudebar_0.1.0_linux_amd64.tar.gz"
      sha256 "946e8c759ae0032c930b9e447648a1f07cc2a8c9524392d753b35c296dcbfef5"
      define_method(:install) do
        bin.install "claudebar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LabLeaks/claudebar/releases/download/v0.1.0/claudebar_0.1.0_linux_arm64.tar.gz"
      sha256 "01176fa31a4a084bddc3654f45a4da574112bf7a9c00551ed639c436c259b462"
      define_method(:install) do
        bin.install "claudebar"
      end
    end
  end

  test do
    system "#{bin}/claudebar", "--version"
  end
end
